### ISSUE TITLE
How do we handle protected images? 

### ISSUE THREAD

**Issue by PradeepShetty14** [devopshq/artifactory-cleanup#20]
Hi Team,

Need your help!!! @allburov @jetersen @Tim55667757 @fishhead108 @Boltyk 

I am trying to filter out artifacts which has **retention-interval=forever**. 
I am using this rule rules.property_neq('retention-interval','forever')
however when I try to execute, the output provides artifacts which has the property value = retention-interval=forever. How do i filter out? These artifacts should not be deleted. 

my reponame.py looks like this

from artifactory_cleanup import rules
from artifactory_cleanup.rules import CleanupPolicy

RULES = [

    # ------ REPOS --------#
    CleanupPolicy(
       'Show artifacts older than 300 days which can be deleted but not protected images',
        rules.repo('repo-name'),
        rules.delete_older_than(days=300),
        rules.property_neq('retention-interval','forever')
    ),
]

**Comment by allburov** [comment]
@PradeepShetty14 how did you fix an issue, could you tell pls?

**Comment by allburov** [comment]
For docker images you should use `delete_docker_images_older_than` rule instead of `rules.delete_older_than(days=300)`
It'll process only `manifest.json` files.

To be protect them from being removed, assign property `retention-internal=forever` to the `manifest.json` file and then use `rules.property_neq('retention-interval','forever')`

I don't have an Artifactory instance now and can't test the solution :(

**Comment by PradeepShetty14** [comment]
Hi @allburov 

We used the below rule
rules.property_neq('retention-interval', 'forever'),

It has filtered out the artifacts which has retention-interval=forever and marked the other artifacts which are empty/some other values. 

So it is working as expected when we tested. 

Thanks a lot.
