### ISSUE TITLE
"or" for rules

### ISSUE THREAD

**Issue by Keonik1** [devopshq/artifactory-cleanup#91]
Now, as I understand, although I may be mistaken, I ask you to correct me in this case, when specifying several rules, they work on the intersection (logical "and"), for example "`DeleteNotUsedSince`" and "`DeleteOlderThanNDaysWithoutDownloads`", it will take the intersection, although logically I would like to do a union (logical "or") here.

I don't know, maybe there is a workaround for this, I didn't think of something, divide it into two identical stages - it's very inconvenient in the debug, because it checks the same files 2 times and deletes them 2 times.

**Comment by allburov** [comment]
@Keonik1 hi! Sorry for the long response - yes, the rules work as logical AND - a file must be valid for all rules in the policy.
Exactly, you should separate rules into two policies - one with `DeleteNotUsedSince` and another with `DeleteOlderThanNDaysWithoutDownloads`

>it checks the same files 2 times and deletes them 2 times.
I don't think so, because the first policy will remove the file and the second won't even see it.
