### ISSUE TITLE
Output format to Json

### ISSUE THREAD

**Issue by usinelogicielle** [devopshq/artifactory-cleanup#99]
We would like a feature request to have the output table to Json format.

The PrettyTable libraries can do it : https://pypi.org/project/prettytable/ 
If I have time, I would propose a PR

**Comment by allburov** [comment]
>If I have time, I would propose a PR
It'd be great!

I think we could add a `--output /path/to/filename.json` argument to handle it and dump all data there at the end of the script.
One problem tho - right now we print it on each policy, so we'll have to either use create a new file per each policy and provide a folder path instead `--output-folder /path/for/files/` or to save multiple json in a single file.

I know YAML supports it with `---` separator, but I'm not sure that JSON allows to do it too and we wouldn't want to add our-own-json-format...  
What do you think about using yaml format instead of json?

For exporting I used [tablib](https://tablib.readthedocs.io/en/stable/) - it'd allow us to export in whatever format a user has specified, but it's not necessary.
